quarkus:
  http:
    port: 8080

  datasource:
    db-kind: postgresql

"%dev":
  quarkus:
    http:
      port: 8844

    hibernate-orm:
      database:
        generation: drop-and-create
      log:
        sql: true

bot:
  telegram:
    my-telegram-bot:
      username: "<bot-username>"
      token: "<bot-token>"
